### PR TITLE
Tag list improvements

### PR DESCRIPTION
**Pull request by XBeg9**
Add tap handler
Add selected background color and selected state
Add selected tags method

### CODE REVIEW

**Comment by XBeg9** [comment]
Should close also close #6

**Comment by xhacker** [comment]
Hey @XBeg9, really appreciate your contribution! However, this seems to break the ability to change the color of all tags via Interface Builder (try building the sample project). Can you check and fix it? Also, there seems to be a breaking change to the `tagPressed:sender:` delegate method. Can you update the sample project and the documentation? Thanks!

**Comment by XBeg9** [comment]
@xhacker please check it, fixed all issues + updated Sample project.

**Comment by XBeg9** [comment]
@xhacker any luck to check it?

**Comment by xhacker** [comment]
Looks good to me, thanks!

**Pull request merged**
