### PR TITLE
New Feature : Deselect all tags at once

### PR DESCRIPTION
**Pull request by HusamAamer**
Long press one of views to **deselect all tags except the long pressed one.**
This piece of code is very useful when you want to pick one or few number of certain tags (Categories in my case) from bunch of them.

ezgif com-crop

### CODE REVIEW

**Comment by xhacker** [comment]
Thank you!

**Comment by HusamAamer** [comment]
My pleasure ☺️

**Comment by RomanVolkov** [comment]
How I can disable this feature?

**Comment by RomanVolkov** [comment]
I found solution, maybe someone will need it too. just set property
.onLongTap = nil for TagView item after call .addTag() method

**Pull request merged**
