### PR TITLE
Feature/remove button

### PR DESCRIPTION
**Pull request by Benuuu**
Update PR #31 @entotsu with the changes @xhacker requested.

- Squashes some changes that became redundant.
- Fixes the padding around the remove button
- Moves the CloseButton into its own class and merges it with DrawCloseView

screen shot 2016-02-11 at 5 54 43 pm

### CODE REVIEW

**Comment by entotsu** [comment]
Awesome :+1:

**Comment by Benuuu** [comment]
Hold off on merging this.  I'm running into an issue where it's not correctly copying over the CloseButton file.

**Comment by Benuuu** [comment]
Okay should be fixed by b780655

**Comment by xhacker** [comment]
Thank you @Benuuu @entotsu, sorry for the delay!

**Pull request merged**
